apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:                    # Include tất cả files
- 00-namespace.yaml
- 01-config.yaml
- 02-database.yaml
- 03-backend.yaml
- 04-frontend.yaml
commonLabels:                 # Labels chung
  project: ecommerce-badminton
